# Generated by Django 5.2.4 on 2025-09-16 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_lettertemplate_studentletter_letterrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettertemplate',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='studentletter',
            name='template',
        ),
        migrations.RemoveField(
            model_name='studentletter',
            name='student',
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_template', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('STAFF_VERIFIED', 'Staff Verified'), ('ADMIN_VERIFIED', 'Admin Verified'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_letters', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who created/saved this letter (student or staff/admin who uploaded template)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STAFF_VERIFIED', 'Staff Verified'), ('ADMIN_VERIFIED', 'Admin Verified'), ('REJECTED_BY_STAFF', 'Rejected by Staff'), ('REJECTED_BY_ADMIN', 'Rejected by Admin'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.letter')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LetterRequest',
        ),
        migrations.DeleteModel(
            name='LetterTemplate',
        ),
        migrations.DeleteModel(
            name='StudentLetter',
        ),
    ]
