# Generated by Django 5.2.5 on 2025-09-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff_date_joined_staff_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='date_joined',
        ),
    ]
