# Generated by Django 5.2.5 on 2025-09-17 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_staff_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='staff_avatars/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
