# Generated by Django 5.2.5 on 2025-09-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_staff_avatar_staff_date_joined_staff_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='request',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
