# Generated by Django 5.2.4 on 2025-09-18 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff_profile', '0001_initial'),
        ('accounts', '0009_request_requesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_requests', to='Staff_profile.staffprofile'),
        ),
    ]
