# Generated by Django 5.2.4 on 2025-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_request_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='staff_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
