# Generated by Django 5.2.4 on 2025-09-18 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='media',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('mixed', 'Mixed')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='notice_videos/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
