# Generated by Django 5.2.4 on 2025-09-20 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_notice_options_remove_notice_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.notice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='accounts.notice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledged_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('notice', 'student')},
            },
        ),
    ]
