# Generated by Django 5.2.5 on 2025-12-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_department_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('PRINCIPAL', 'Principal'), ('DEPT_ADMIN', 'Dept Admin'), ('DEPT_STAFF', 'Dept Staff'), ('DEPT_STUDENT', 'Dept Student')], default='DEPT_STUDENT', max_length=20),
        ),
    ]
