# Generated by Django 5.2.5 on 2025-12-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate')], default='UG', max_length=5),
        ),
    ]
