# Generated by Django 5.2.5 on 2025-12-13 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_department_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_verification', 'Pending Verification'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=25),
        ),
        migrations.AddField(
            model_name='timetable',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL),
        ),
    ]
