# Generated by Django 5.2.5 on 2025-12-16 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_timetable_department_timetable_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('advisor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor1_classes', to=settings.AUTH_USER_MODEL)),
                ('advisor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor2_classes', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_advisors', to='accounts.department')),
            ],
            options={
                'unique_together': {('department', 'year')},
            },
        ),
    ]
