# Generated by Django 5.2.5 on 2025-12-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_classadvisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Display Name'),
        ),
    ]
