# Generated by Django 5.2.5 on 2026-02-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_accountrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
