# Generated by Django 5.2.5 on 2026-02-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_classadvisor_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='class_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='hour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='mode_of_hour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='mode_of_teaching',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='topics_covered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='unit_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
