# Generated by Django 5.2.5 on 2026-02-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_attendancesession_class_mode_attendancesession_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
