# Generated by Django 5.2.5 on 2026-02-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_scheduleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_roles',
            field=models.JSONField(default=list, help_text="['DEPT_ADMIN', 'DEPT_STAFF', 'DEPT_STUDENT']"),
        ),
    ]
