# Generated by Django 5.2.5 on 2026-02-19 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_notice_target_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='target_roles',
        ),
        migrations.AddField(
            model_name='notice',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_notices', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_dept_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_student',
            field=models.BooleanField(default=True),
        ),
    ]
