# Generated by Django 5.2.5 on 2026-04-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_pushdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='crt_eligible',
        ),
        migrations.RemoveField(
            model_name='student',
            name='crt_status',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('Studying', 'Studying'), ('Discontinued', 'Discontinued')], default='Studying', max_length=20),
        ),
    ]
