# Generated by Django 5.2.4 on 2026-04-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_passwordresetotp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
