# Generated by Django 5.2.5 on 2025-09-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
