# Generated by Django 5.2.5 on 2026-04-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
